/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AdminPageHeader: typeof import('./src/components/Admin/AdminPageHeader.vue')['default']
    CallToAction: typeof import('./src/components/Landing/CallToAction.vue')['default']
    CategoryHero: typeof import('./src/components/Portfolio/CategoryHero.vue')['default']
    CategoryTiles: typeof import('./src/components/Portfolio/CategoryTiles.vue')['default']
    Cta: typeof import('./src/components/About/Cta.vue')['default']
    ErrorMessage: typeof import('./src/components/_helpers/ErrorMessage.vue')['default']
    EventsInquiry: typeof import('./src/components/Portfolio/EventsInquiry.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    FindProduct: typeof import('./src/components/Merchant/FindProduct.vue')['default']
    FormSection: typeof import('./src/components/Contact/FormSection.vue')['default']
    Gallery: typeof import('./src/components/Portfolio/Gallery.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/About/Hero.vue')['default']
    Intro: typeof import('./src/components/Landing/Intro.vue')['default']
    OAuthCallback: typeof import('./src/components/OAuthCallback.vue')['default']
    PlacementMap: typeof import('./src/components/Admin/PlacementMap.vue')['default']
    Portfolio: typeof import('./src/components/Landing/Portfolio.vue')['default']
    PricingSection: typeof import('./src/components/Investment/PricingSection.vue')['default']
    ProductList: typeof import('./src/components/Merchant/ProductList.vue')['default']
    QuickFacts: typeof import('./src/components/About/QuickFacts.vue')['default']
    ResponsivePhoto: typeof import('./src/components/Photo/ResponsivePhoto.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveProductDialog: typeof import('./src/components/Merchant/SaveProductDialog.vue')['default']
    Specialties: typeof import('./src/components/Landing/Specialties.vue')['default']
    Story: typeof import('./src/components/About/Story.vue')['default']
    Testimonial: typeof import('./src/components/Landing/Testimonial.vue')['default']
    TurnstileWidget: typeof import('./src/components/_helpers/TurnstileWidget.vue')['default']
    UnDraw: typeof import('./src/components/_helpers/UnDraw/UnDraw.vue')['default']
    UserList: typeof import('./src/components/Merchant/UserList.vue')['default']
    ViewProduct: typeof import('./src/components/Merchant/ViewProduct.vue')['default']
  }
}
